### ISSUE TITLE
pasteboard plugins require windows developer mode opening

### ISSUE THREAD

**Issue by sherry0429** [MixinNetwork/flutter-plugins#132]
first, thanks your great work,
when i use pasteboard plugins, that flutter raise exception like this:

```
Exception: Building with plugins requires symlink support.

Please enable Developer Mode in your system settings. Run
  start ms-settings:developers
to open settings.

```

I want to know why this plugin require symlink support? thanks, because of some security issues, I must figure out it,

**Comment by boyan01** [comment]
> I want to know why this plugin require symlink support? 

Because flutter_tool required it.  

Flutter build app for windows with plugins required symlink support. 

Not only this plugin, but other plugins will also require this option on. such as `window_manager`

if you want figure out it, here is the flutter tool source code, maybe you can find more things in this codes. https://github.com/flutter/flutter/blob/803ef6a456c3127a4c5509eb726f9319569edb3d/packages/flutter_tools/lib/src/flutter_plugins.dart#L1031

**Comment by sherry0429** [comment]
ok. thanks!
