### ISSUE TITLE
[desktop_drop 0.3.3] does not work on debug, but it >does< work on release

### ISSUE THREAD

**Issue by Eerey** [MixinNetwork/flutter-plugins#140]
Hi, it seems like `desktop_drop 0.3.3` does not work on debug (env: Windows). Do I need to configure something for the debug build in order to make it work?

When I try it in debug, I get the "Windows Cross" -> X

**Comment by Eerey** [comment]
Any news on that?

**Comment by boyan01** [comment]
I tested on my win11 PC, however the example seems works fine in debug mode.

https://user-images.githubusercontent.com/17426470/194275182-c74839c9-0a2a-4beb-92da-54e7ae8919ea.mp4


So could you provider a example so that I can find out what cause the wrong?  (If the problem is with the Windows version, I may not be able to help because I don't have a PC with win10 development environment...

**Comment by yaitmou** [comment]
For some reason, the video you linked didn't show for me!!! Nevertheless, I am on Windows 11 and I run the example found under [desktop_drop repos](https://github.com/MixinNetwork/flutter-plugins/tree/main/packages/desktop_drop/example)

**Comment by Elixell** [comment]
I have the same issue on win 11. Works fine in release mod.

**Comment by hwkim1127** [comment]
Same issue here on win 10.
Also, works fine in release mode.

flutter : 3.3.10
windows : 10.0.19044.2486
Visual Studio : 2022 17.4.1

**Comment by boyan01** [comment]
No idea for this. but it sounds like https://github.com/MixinNetwork/flutter-plugins/issues/161

@hwkim1127  are you running your debug app as administrator? Does the debug app works if you open the exe in `build\windows\runner\Debug`  by `File Explorer` ?

**Comment by boyan01** [comment]
closed for no reponse, un reproducible.
