### ISSUE TITLE
[Pasteboard] Copy pasting an image file on macOS has incorrect image bytes.

### ISSUE THREAD

**Issue by BirjuVachhani** [MixinNetwork/flutter-plugins#147]
If you copy an image file and paste it, `Pasteboard.image` is not null but the bytes are rendered in Flutter, it's not the actual image. Instead, it looks like this:

<img src="https://user-images.githubusercontent.com/20423471/190990315-2def125d-fe29-4b1c-99bd-1054ae2160b7.png"  width="200px"/>

When the actual image looks like this:

<img src="https://user-images.githubusercontent.com/20423471/190990489-a2d521af-eefb-49a9-bbd0-329814a10f17.jpeg" width="200px"/>

Code:

```dart
final Uint8List? imageBytes = await Pasteboard.image;
```

Note that it works just fine on web.

**Comment by boyan01** [comment]
Sorry for delay, can you give me  a simple reproducable code here? and what platform and flutter version are you using?

I just run the `package/pasteboard/example` on macOS with flutter 3.3. The image paste seems works fine.

<img width="524" alt="image" src="https://user-images.githubusercontent.com/17426470/191512730-6e767c83-63d5-401d-9aec-c8fc0f320b1b.png">

**Comment by borjandev** [comment]
@BirjuVachhani can you provide more information on how you got it to work on the web? 

Such as the flutter version and the reproducible steps?

@boyan01 In order to reproduce the issue, copy a local image file, instead of copying the image data directly from Preview or similar.

For reference, Google Docs (even on web) supports copying an imagine file (as file) and upon pasting it it correctly displays the full inline image content which is expected behaviour for images at the very least.

Flutter (Channel stable, 3.3.0, on macOS 13.0 22A380 darwin-arm

https://user-images.githubusercontent.com/64651636/204139197-fcc1ebdd-068e-4034-bdfc-080890251134.mov

**Comment by BirjuVachhani** [comment]
@borjandev Thank you for providing a demo for this.

For web, Pasteboard is not working in this case. So I am using `html.document.onPaste` stream to listen to paste events on a browser get image from the event data.

```dart
html.document.onPaste.listen((event) {
  final html.DataTransferItemList? items = event.clipboardData?.items;
  if (items != null) {
    for (int i = 0; i < items.length!; i++) {
      final String? type = items[i].type?.toString();
      final html.File? file = items[i].getAsFile();
    }
  }
});
```

**Comment by boyan01** [comment]
Thanks for the detailed description @borjandev 


in this situation, should use `await Pasteboard.files()` to get the file instead of `Pasteboard.image`
