### ISSUE TITLE
[desktop_webview_window] 用户反馈的两个问题

### ISSUE THREAD

**Issue by feimenggo** [MixinNetwork/flutter-plugins#198]
用户反馈的两个问题，而我自己的电脑上没有复现这些问题。

#### 第一个问题：
![image](https://user-images.githubusercontent.com/12608693/211780881-691d3d42-b47b-49aa-8696-2406815fae20.png)

#### 第二个问题：
用户说Edge浏览器被他卸载了，但是重新安装上Edge还是不行。
![image](https://user-images.githubusercontent.com/12608693/211781206-4c030d62-beb2-4464-952e-057586197527.png)

**Comment by boyan01** [comment]
## Q1:

I don't known.

## Q2:

The reuquirement of WebView2 is `WebView2 Runtime`, but not `Edge Browser`.  the setup of `WebView2 Runtime` can download from here: https://go.microsoft.com/fwlink/p/?LinkId=2124703

-----

In addition, multiple question or bug report should be submitted in multiple Issues instead of mixed in one Issue.

**Comment by feimenggo** [comment]
Ok, thanks.
